### PR TITLE
Update Deployment and Ingress apiVersions

### PR DESCRIPTION
**Pull request by rjeberhard**
This PR resolves issue #1769, which we've been asked to expedite. The issue only mentions the Deployment apiVersion, but while reviewing recent changes to Kubernetes, I noticed that both Ingress and Deployment have been long-since moved to new apiVersions and the updated versions are now supported by our minimum Kubernetes version (1.14).

Therefore, I've updated references to both Deployment and Ingress in this PR.

### CODE REVIEW

**Comment by rjeberhard** [comment]
Converting this to draft because I realized there are more files that need to change.

**Comment by rjeberhard** [comment]
Okay, fixed... Tests running now. I needed to update the Java classes too.

**Comment by alai8** [comment]
Do we also need to update apps/v1beta to apps/v1 in these files? 
./src/integration-tests/kubernetes/logstash.yaml
./src/integration-tests/kubernetes/elasticsearch.yaml
./src/integration-tests/kubernetes/kibana.yaml
./kubernetes/samples/scripts/elasticsearch-and-kibana/elasticsearch_and_kibana.yaml

**Comment by rjeberhard** [comment]
Yes, thanks, @alai8. Those files are updated now.

**Pull request merged**
