### PR TITLE
Add situational configuration override tests with running domain

### PR DESCRIPTION
**Pull request by sankarpn**
Add new tests to override config.xml and JDBC system resource after a domain was created and started.
The tests edits the configOverrides configmap and changes the config.xml and JDBC system resource modules tp apply it to the running domain.

The tests restarts the domain by setting restartPolicy to NEVER and IF_NEEDED to run the introsprector and reapply the override files.

### CODE REVIEW

**Comment by sankarpn** [comment]
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2084/console

[ERROR] Failures: 
[ERROR]   ItMonitoringExporter.test19_EndToEndViaChart:825->installPrometheusGrafanaViaChart:1144
[INFO] 
[ERROR] Tests run: 98, Failures: 1, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M3:verify (integration-tests) @ operator-integration-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Build Tools 1.0 .................................... SUCCESS [  1.173 s]
[INFO] weblogic-kubernetes-operator 2.3.0 ................. SUCCESS [  3.117 s]
[INFO] json-schema 2.3.0 .................................. SUCCESS [ 16.324 s]
[INFO] jsonschema-maven-plugin Maven Mojo 2.3.0 ........... SUCCESS [ 10.210 s]
[INFO] operator-model 2.3.0 ............................... SUCCESS [ 19.034 s]
[INFO] operator-swagger 2.3.0 ............................. SUCCESS [  5.561 s]
[INFO] operator-runtime 2.3.0 ............................. SUCCESS [ 45.172 s]
[INFO] operator-integration-tests 2.3.0 ................... FAILURE [  06:49 h]
[INFO] installation-tests 2.3.0 ........................... SKIPPED
[INFO] Project Reports 2.3.0 .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:51 h
[INFO] Finished at: 2019-08-01T00:14:14-07:00
[INFO] ------------------------------------------------------------------------

**Comment by tbarnes-us** [comment]
Can you modify the test to shutdown and restart the domain via life-cycle instead of by deleting the domain crd?

**Comment by sankarpn** [comment]
> Can you modify the test to shutdown and restart the domain via life-cycle instead of by deleting the domain crd?
Yes sure.

**Comment by sankarpn** [comment]
> Can you modify the test to shutdown and restart the domain via life-cycle instead of by deleting the domain crd?
Yes sure.
Done.

**Pull request merged**
