### PR TITLE
Add shell scripts to run v8o tests in Jenkins

### PR DESCRIPTION
**Pull request by sankarpn**
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/23/

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Are you setting a Jenkin job to verify e2e script ?

**Comment by sankarpn** [comment]
> Are you setting a Jenkin job to verify e2e script ?

Yes. The Jenkins job creates a kind cluster, deploys v8o and runs the vz integration tests

**Review by maggiehe00 — APPROVED** [review]
LGTM

**Review by vanajamukkara — APPROVED** [review]

**Review by anpanigr — APPROVED** [review]
lgtm

**Pull request merged**
