### PR TITLE
Upgrade DB operator to version 0.2.0

### PR DESCRIPTION
**Pull request by sankarpn**
Update the Oracle database Operator to version 0.2.0

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11489/

### CODE REVIEW

**Comment by sankarpn** [comment]
> Modify the file integration-tests/src/test/resources/bash-scripts/images.properties Update the description with latest Jenkin Result

Result included and images.properties updated

**Review by anpanigr — APPROVED** [review]
lgtm

**Review by anpanigr — COMMENTED** [review]
Did you Verify the issue found in OWLS-96073 (Cert: Port ItTestDBOperator test into OKD )

**Review by maggiehe00 — APPROVED** [review]
LGTM

**Comment by sankarpn** [comment]
> Did you Verify the issue found in OWLS-96073 (Cert: Port ItTestDBOperator test into OKD )

We don't run the DBOperator tests in OKD

**Pull request merged**
