### PR TITLE
Updated helm chart repository url for prometheus to reflect the recent changes

### PR DESCRIPTION
**Pull request by marinakog**
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3124/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3127/

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Can you check if we need to modify any sample documentation.

**Comment by marinakog** [comment]
> Can you check if we need to modify any sample documentation.

checked , there is  nothing to correct in the sample document

**Review by anpanigr — COMMENTED** [review]
We have one failure on parallel run.

**Comment by marinakog** [comment]
> We have one failure on parallel run.

it is not related to my change and looks intermittent 
did not find file /u01/shared/domains/domainonpv-lqaw/servers/admin-server/data/store/default/_WLS_ADMIN-SERVER000000.DAT in pod domainonpv-lqaw-admin-server in namespace ns-lqaw ==> expected: <true> but was: <false>

**Review by anpanigr — APPROVED** [review]
LGTM based on jenkin run

**Review by rjeberhard — APPROVED** [review]

**Pull request merged**
