### PR TITLE
Remove wko integration test dependency from the directory operator/integration-tests

### PR DESCRIPTION
**Pull request by hzhao-github**
Some integration tests use operator/integration-tests/apps/testwebapp.war. copy this file to integration-tests/src/test/resources/apps and changed test suites accordingly

Jenkins job:

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11025/

Jenkins job with latest changes:

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11045
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11046

three failures, I don't see any of them using testwebapp.war and the error messages are either failed to start managed servers or failed to delete intruspector. So they shouldn't be caused by this change. 

Jenkins job with latest changes:

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11241
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11244

Jenkins sequential runs:
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/717/
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/718

### CODE REVIEW

**Review by rjeberhard — APPROVED** [review]

**Review by anpanigr — COMMENTED** [review]
(a) Can we create the testweabapp.war on the fly, instead of check-in the war file in repo.
(b) remove the file operator/integration-tests/apps/testwebapp.war
(c) remove another occurrence  kubernetes/samples/charts/application/testwebapp.war

**Comment by hzhao-github** [comment]
@anpanigr where can I find the source code of testweabapp.war for (a) Can we create the testweabapp.war on the fly, instead of check-in the war file in repo.

**Comment by anpanigr** [comment]
> @anpanigr where can I find the source code of testweabapp.war for (a) Can we create the testweabapp.war on the fly, instead of check-in the war file in repo.
<operator(pani-1)>jar -tvf operator/integration-tests/apps/testwebapp.war
     0 Tue Nov 21 15:17:48 UTC 2017 META-INF/
   133 Tue Nov 21 15:17:46 UTC 2017 META-INF/MANIFEST.MF
     0 Tue Nov 21 15:17:48 UTC 2017 WEB-INF/
     0 Tue Nov 21 15:17:48 UTC 2017 WEB-INF/classes/
  1001 Tue Nov 21 15:16:16 UTC 2017 index.jsp
   934 Tue Nov 21 15:16:58 UTC 2017 WEB-INF/web.xml
  1121 Tue Nov 21 15:17:12 UTC 2017 WEB-INF/weblogic.xml
     0 Tue Nov 21 15:17:48 UTC 2017 META-INF/maven/
     0 Tue Nov 21 15:17:48 UTC 2017 META-INF/maven/com.oracle.weblogic/
     0 Tue Nov 21 15:17:48 UTC 2017 META-INF/maven/com.oracle.weblogic/testwebapp/
  1170 Tue Nov 21 15:15:04 UTC 2017 META-INF/maven/com.oracle.weblogic/testwebapp/pom.xml
   112 Tue Nov 21 15:17:48 UTC 2017 META-INF/maven/com.oracle.weblogic/testwebapp/pom.properties

**Comment by hzhao-github** [comment]
@anpanigr We can build it on fly, however, these are description files only, no build/compiling needed. I feel that it's ok to keep .war file, But if you want me to build it on fly, I can do it

**Comment by anpanigr** [comment]
> @anpanigr We can build it on fly, however, these are description files only, no build/compiling needed. I feel that it's ok to keep .war file, But if you want me to build it on fly, I can do it

In a Opensource project we should not check-in any binary file.

**Review by anpanigr — COMMENTED** [review]
How about removal of weblogic-kubernetes-operator/blob/remove_dependency/operator/integration-tests/apps/opensessionapp.war

**Comment by hzhao-github** [comment]
Just checked, no one uses opensessionapp.war

/Users/huilingzhao/ProjectSource/operator/main/weblogic-kubernetes-operator
bash-3.2$ grep -R "opensessionapp.war" *

**Review by anpanigr — APPROVED** [review]
lgtm

**Comment by hzhao-github** [comment]
Waiting for Jenkins results of Sequential runs

**Pull request merged**
