### PR TITLE
add 2.1 changes

### PR DESCRIPTION
**Pull request by rosemarymarano**

### CODE REVIEW

**Comment by markxnelson** [comment]
fwiw i think @rjeberhard is going to call this 2.0.1, not 2.1

**Comment by rosemarymarano** [comment]
Oh, I thought you won that debate. I'll change it.

**Comment by rosemarymarano** [comment]
Not needed.

**Comment by rjeberhard** [comment]
You two make me laugh...  We are going to have a bug fix release, called 2.0.1, including OpenShift certification.  Then, we'll still have release 2.1, including InitContainers and whatever else is ready (Istio, FMW/JRF, etc.)

**Pull request closed without merging**
