### PR TITLE
Fix validate scripts target to run in windows

### PR DESCRIPTION
**Pull request by sankarpn**
If running clean build targets on integration-tests in windows it is failing to run the bash script with no associated executable to run the script. This change introduces bash as the executable while running the shell script.

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8234/

### CODE REVIEW

**Comment by alai8** [comment]
Hi Sankar, I have a pending PR 2729 to merge this execution block to the other exec-maven-plugin. It is for removing a build warning (see PR 2729 for details). Do you mind moving the execution block in your change and I will withdraw my PR? Thanks!

**Comment by sankarpn** [comment]
> Hi @sankarpn , I have a pending PR 2729 to merge this execution block to the other exec-maven-plugin. It is for removing a build warning (see PR 2729 for details). Do you mind moving the execution block in your change and I will withdraw my PR? Thanks!

Hi @alai8 , I have moved the block and added my changes as well to this PR. You can close your PR. Thanks

**Review by alai8 — APPROVED** [review]
LGTM. Thanks!

**Review by anpanigr — APPROVED** [review]
lgtm

**Pull request merged**
