### PR TITLE
Retry and wait between retries of failed downloads jenkins-ignore

### PR DESCRIPTION
**Pull request by hzhao-github**

### CODE REVIEW

**Comment by hzhao-github** [comment]
Jenkins job passed

http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2646/consoleFull

**Comment by hzhao-github** [comment]
the second Jenkins run passed as well

wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2659/console

**Comment by hzhao-github** [comment]
Regarding whether the changes fix the intermittent issue, I am not sure either because it's a HTTP 403 error. What I do in this changes as you can see:

1. separate two wget calls to wipe off the risk that they step on each other's toes 
2. Add wait and retry upon failures
3. print server response

let's keep our finfer's crossed

I have submitted two more Jenkins jobs:

http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2670/console
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2671/console

**Comment by hzhao-github** [comment]
Jenkins job passed

http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2671/consoleFull

**Comment by hzhao-github** [comment]
loggingExporter passed in two more Jenkins jobs

http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2676/consoleFull
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2677/consoleFull

**Comment by hzhao-github** [comment]
Jenkins job with latest changes passed 
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2691/consoleFull

**Comment by anpanigr** [comment]
The testware changes look  OK to me

**Pull request merged**
