### PR TITLE
change java integration tests to use load balancer helm chart for traefik

### PR DESCRIPTION
**Pull request by vanajamukkara**
Tests are changed to use load balancer helm chart for traefik instead of sample scripts.
One load balancer is used for all the domains with host routing for ingress.
Apache load balancer test is commented for now as its not yet changed to helm chart.

On jenkins, integration tests have intermittent failures on develop branch, I see the same failures when ran with these changes. Dongbo is aware of these failures.
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/275/console

@anpanigr @doxiao

### CODE REVIEW

**Comment by doxiao** [comment]
There is one failure/error that I did not see before your change. Not sure if it is related to the change in this PR.

[ERROR] test3CreateDomainInTest1NS(oracle.kubernetes.operator.ITOperator)  Time elapsed: 553.988 s  <<< ERROR!
java.lang.RuntimeException: FAILURE: Cluster replica doesn't match with scaled up size 4/3
	at oracle.kubernetes.operator.BaseTest.testWLDFScaling(BaseTest.java:305)
	at oracle.kubernetes.operator.ITOperator.test3CreateDomainInTest1NS(ITOperator.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)

**Comment by vanajamukkara** [comment]
The error is not related to the changes in this PR, it is the WLDF scaling test.  The test is calling the webapp 20 times to verify load balancing is happening, it is possible that the scaling action gets triggered more than once based on the rule defined in the WLDF module. This issue is also intermittent as scaling up takes time. I will be changing the test to make sure that after scale up replica is greater than before scale up to fix this issue.

**Comment by doxiao** [comment]
The new failure showed up in all runs using this branch on Jenkins, so I am not sure if it is intermittent. It seems to be different from the intermittent issue that I am looking into.

**Comment by doxiao** [comment]
Thanks!

**Pull request merged**
