### PR TITLE
OWLS76160 - Adding situational configuration tests for domain in image

### PR DESCRIPTION
**Pull request by sankarpn**

### CODE REVIEW

**Comment by sankarpn** [comment]
All the situational config tests passed in local as well as Jenkins runs.
Running the full IT suite....

**Comment by tbarnes-us** [comment]
I did a relatively quick general review, and the change looks good to me. Let me know if there's a specific area you'd like me to double-check.  Vanaja can hopefully be a bit more thorough given her strong familiarity with the test framework.

**Comment by sankarpn** [comment]
> 
> 
> I did a relatively quick general review, and the change looks good to me. Let me know if there's a specific area you'd like me to double-check. Vanaja can hopefully be a bit more thorough given her strong familiarity with the test framework.

Thanks Tom. I didn't make any changes to the test, just put a wrapper around the tests to run in both PV and InImage domain models.

**Comment by sankarpn** [comment]
The full integration test suite passed.

http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2349/consoleFull

[INFO] 
[INFO] Build Tools 1.0 .................................... SUCCESS [  1.075 s]
[INFO] weblogic-kubernetes-operator 2.3.0 ................. SUCCESS [  2.193 s]
[INFO] json-schema 2.3.0 .................................. SUCCESS [ 11.185 s]
[INFO] jsonschema-maven-plugin Maven Mojo 2.3.0 ........... SUCCESS [  7.059 s]
[INFO] operator-model 2.3.0 ............................... SUCCESS [ 12.782 s]
[INFO] operator-swagger 2.3.0 ............................. SUCCESS [  3.795 s]
[INFO] operator-runtime 2.3.0 ............................. SUCCESS [ 32.026 s]
[INFO] operator-integration-tests 2.3.0 ................... SUCCESS [  06:24 h]
[INFO] installation-tests 2.3.0 ........................... SUCCESS [  2.349 s]
[INFO] Project Reports 2.3.0 .............................. SUCCESS [  0.940 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:25 h
[INFO] Finished at: 2019-08-22T03:34:13Z
[INFO] ------------------------------------------------------------------------

**Pull request merged**
