### PR TITLE
changing script to require bash

### PR DESCRIPTION
**Pull request by robertpatrick**
Fixing #2819 in main

### CODE REVIEW

**Review by rjeberhard — DISMISSED** [review]

**Comment by ankedia** [comment]
AFAIK, busybox doesn't have bash shell. Will this work in environments that doesn't have bash shell?

**Comment by rjeberhard** [comment]
Oh, right... I forgot about that.

**Comment by robertpatrick** [comment]
@rjeberhard @ankedia OK, I didn't think about that.  Then the right solution is to use `.` instead of `source` (which is not a POSIX-compliant command)

**Review by rjeberhard — APPROVED** [review]

**Comment by ankedia** [comment]
> @rjeberhard @ankedia OK, I didn't think about that. Then the right solution is to use `.` instead of `source` (which is not a POSIX-compliant command)
[ANIL] Ok. I think `source` is also used in other scripts such as `startServer.sh` and `utils.sh`. However those scripts run in the main container which I assume is based on OEL. If this is the only non-POSIX compliant command, then the change looks good to me.

**Pull request merged**
