### PR TITLE
add ItMiiNewCreateAuxImage to okd profile

### PR DESCRIPTION
**Pull request by maggiehe00**
The essential change of this PR is to add dockerLogin into OKD Jenkins Build script.
(Please see function dockerLogin() in https://build.weblogick8s.org:8443/job/wko-okd-test/configure)

OKD Jenkins job 
https://build.weblogick8s.org:8443/job/wko-okd-test/106/testReport/oracle.weblogic.kubernetes/

### CODE REVIEW

**Review by anpanigr — APPROVED** [review]
lgtm

**Review by bhavaniravichandran — APPROVED** [review]
LGTM

**Comment by maggiehe00** [comment]
> Please update the copyright to 2022

@robertpatrick Done. Thanks!

**Comment by hzhao-github** [comment]
LGTM

**Review by hzhao-github — APPROVED** [review]

**Review by robertpatrick — APPROVED** [review]

**Pull request merged**
