### PR TITLE
Added container name when copying archive files jenkins-ignore

### PR DESCRIPTION
**Pull request by hzhao-github**

### CODE REVIEW

**Comment by hzhao-github** [comment]
Two Jenkins jobs kicked off:

http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2769/
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2770/

**Comment by hzhao-github** [comment]
test passed

http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2769/

**Comment by vanajamukkara** [comment]
Adding comments I posted on slack 

@huizhao for the copy issue, exit code 126 you mentioned is permission issue..so have u checked or added any debug to print or check the permissions of file ?

Vanajakshi Mukkara 3:18 PM
Also TestUtils.kubectlcp() is used only in ItElasticLogging..other test classes use TestUtils.copyFileViaCat() to copy war files or other scripts ...there are no issues with that ...If you are making sure that the file is downloaded, you may want to try switching to copyFileViaCat()...I don't think adding container name will make any difference ...

**Comment by hzhao-github** [comment]
@vanajamukkara , as I mentioned several times in daily meeting, exit code 126 could be permission  or proxy issue. Yes, I added bunch of ls -l to print out the contents of diff dir to debug the the future. Again, no I can't use copy via cat because the test copies archive

**Comment by vanajamukkara** [comment]
> 
> 
> @vanajamukkara , as I mentioned several times in daily meeting, exit code 126 could be permission or proxy issue. Yes, I added bunch of ls -l to print out the contents of diff dir to debug the the future. Again, no I can't use copy via cat because the test copies archive

Other tests are using TestUtils.copyFileViaCat()  to copy war file, take a look at Domain.deployWebAppViaWlst()

**Comment by hzhao-github** [comment]
I tried but failed

**Comment by hzhao-github** [comment]
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2781/console

**Comment by hzhao-github** [comment]
LoggingExporter test passed in http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2781/consoleFull

**Pull request merged**
