### PR TITLE
Backport: Refactor ItTwoDomainLoadBalancer class for separate LoadBalancers to release/3.3

### PR DESCRIPTION
**Pull request by xiancao**
Backport the task for refactoring ItTwoDomainLoadBalancer class for separate LoadBalancers to release/3.3

Jenkins result: 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8361/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8360/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8359/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8358/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8373/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8378/

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Can u run all the LoadBalancer Tests and Usability Tests in parallel in a single run

**Comment by xiancao** [comment]
updated the parallel test result:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8378/

**Review by anpanigr — APPROVED** [review]
LGTM

**Review by sankarpn — APPROVED** [review]
lgtm

**Review by maggiehe00 — APPROVED** [review]

**Pull request merged**
