### PR TITLE
Backport remote console PR#2649 to release/3.3

### PR DESCRIPTION
**Pull request by maggiehe00**
Single test:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7750/console

Latest test result
release/3.3 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7949/
you can see ItRemoteConsole failed
My PR branch:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7954/testReport/   ItRemoteConsole passed.

### CODE REVIEW

**Comment by xiancao** [comment]
Can you rerun the full suite test (parallel and sequential)? There are too many tests failed.

**Comment by maggiehe00** [comment]
@xiancao I run release/3.3 without my change on kind -new, the result looks not good either
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7805/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7809/

**Comment by robertpatrick** [comment]
@xiancao @anpanigr can you please review this PR and let me know what the outcome is?

**Review by xiancao — APPROVED** [review]

**Review by anpanigr — COMMENTED** [review]
We need to take care of other failures in 3.3 in a separate JIRA

**Review by anpanigr — APPROVED** [review]
lgtm

**Pull request merged**
