### PR TITLE
WIP: updating the traefik ingress for the weblogic admin and cluster servi…

### PR DESCRIPTION
**Pull request by v-2vikc**
…ce for the https redirection and verified the successfull login with the TLS certificate

### CODE REVIEW

**Comment by TheFrogPad** [comment]
Hi Vikram, this example `Ingress` and `ConfigMap` for Traefik looks fine to me.

I would suggest a little more comment for each section. For example, in `/console` routing, note that this allows login as HTTPS frontend redirects to HTTP backed based on the Traefik configuration.

Some documentation links would also be nice to include, the ones I found where:
* https://docs.traefik.io/configuration/backends/kubernetes/
* https://docs.traefik.io/configuration/entrypoints/

Thanks!

**Comment by markxnelson** [comment]
Thank you for your contribution. Please carefully review the CONTRIBUTING.md in this project which provides details of how to contribute.  In particular, you will notice that we can only accept PR's from signatories of the Oracle Contribution Agreement.  If you wish to proceed with your contribution, please update to let me know. Thanks again.

**Comment by v-2vikc** [comment]
> Thank you for your contribution. Please carefully review the CONTRIBUTING.md in this project which provides details of how to contribute. In particular, you will notice that we can only accept PR's from signatories of the Oracle Contribution Agreement. If you wish to proceed with your contribution, please update to let me know. Thanks again.

Hi Nelson, Yes I would like to contribute.

**Comment by markxnelson** [comment]
That's great. Please let me know when you have submitted the OCA.

**Comment by bsmoyers** [comment]
Can one of the admins verify this patch?

**Comment by v-2vikc** [comment]
> > Thank you for your contribution. Please carefully review the CONTRIBUTING.md in this project which provides details of how to contribute. In particular, you will notice that we can only accept PR's from signatories of the Oracle Contribution Agreement. If you wish to proceed with your contribution, please update to let me know. Thanks again.
> 
> Hi Nelson, Yes I would like to contribute.

I have upload the OCA, please review and approve the request.

**Comment by v-2vikc** [comment]
> That's great. Please let me know when you have submitted the OCA.

I have submitted the OCA today

**Comment by markxnelson** [comment]
Thank you very much, I am just confirming the OCA is approved, then we can merge.

**Comment by markxnelson** [comment]
Hi @v-2vikc - I am just following up on this.  I do not see the OCA, could you please confirm the name/username you used?  You can email to me privately at mark.x.nelson at oracle.com

**Pull request closed without merging**
