### PR TITLE
 Make distinct nightly profiles kind-sequential 

### PR DESCRIPTION
**Pull request by maggiehe00**
For kind-sequential 
https://build.weblogick8s.org:8443/job/wko-tmp/44/

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Please compare the sequential result with nightly-sequential run. I do not not see all the WLS/FMW upgrade tests 

https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/275/testReport/oracle.weblogic.kubernetes/ItOperatorWlsUpgrade/

**Comment by maggiehe00** [comment]
@anpanigr When I run that test I purposely commented out some tests to quickly get result. Let me re-run full sequential suite.

**Comment by maggiehe00** [comment]
Please see the latest full sequential run: https://build.weblogick8s.org:8443/job/wko-tmp/41/
Thanks.

**Review by anpanigr — APPROVED** [review]
LGTM

**Review by vanajamukkara — APPROVED** [review]
LG

**Pull request merged**
