### PR TITLE
WIP: Add some debugging for ITElasticLogging test

### PR DESCRIPTION
**Pull request by markxnelson**
This test failed with a file error, it is not clear why, so this PR seeks to add some extra logging to help with problem determination.

Example failure: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1375/testReport/oracle.kubernetes.operator/ItElasticLogging/testWlsLoggingExporter/

```
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at oracle.kubernetes.operator.ItElasticLogging.downloadWlsLoggingExporterJars(ItElasticLogging.java:523)
	at oracle.kubernetes.operator.ItElasticLogging.testWlsLoggingExporter(ItElasticLogging.java:336)
```

### CODE REVIEW

**Comment by vanajamukkara** [comment]
@markxnelson  base branch is master, should be develop

**Comment by markxnelson** [comment]
initial test run https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1386

**Comment by markxnelson** [comment]
On the new test run, the failure to read that file did not occur.  However the test did fail with the by now common pattern of TextUtils.exec() throwing a RE, as can be seen in the log below after the curl rc=6, it immediately goes on to the next prepare() call.

```
<04-28-2020 01:48:09> <INFO> <oracle.kubernetes.operator.ItElasticLogging execSearchQuery> <Command to search: kubectl exec -it weblogic-operator-cf5858d74-7vpwr -n itelastic-opns-58 -c weblogic-operator --request-timeout="20s" -- /bin/bash -c 'curl  --connect-timeout 20 --max-time 20 -X GET http://elasticsearch.default.svc.cluster.local:9200/logstash-2020.04.28/_search?q=log:itelastic-domain-59-admin-server'>
<04-28-2020 01:48:11> <INFO> <oracle.kubernetes.operator.utils.TestUtils exec> <
Command kubectl exec -it weblogic-operator-cf5858d74-7vpwr -n itelastic-opns-58 -c weblogic-operator --request-timeout="20s" -- /bin/bash -c 'curl  --connect-timeout 20 --max-time 20 -X GET http://elasticsearch.default.svc.cluster.local:9200/logstash-2020.04.28/_search?q=log:itelastic-domain-59-admin-server'
return value: 6
stderr = Unable to use a TTY - input is not a terminal or the right kind of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: elasticsearch.default.svc.cluster.local; Unknown error
command terminated with exit code 6
stdout = >
<04-28-2020 01:48:11> <INFO> <oracle.kubernetes.operator.BaseTest createResultAndPvDirs> <Adding file handler, logging to file at /var/lib/jenkins/workspace/weblogic-kubernetes-operator-quicktest/RESULT_ROOT/ItElasticLogging/acceptance_test_tmp/ItElasticLogging.out>
<04-28-2020 01:48:09> <INFO> <oracle.kubernetes.operator.ItElasticLogging execSearchQuery> <Command to search: kubectl exec -it weblogic-operator-cf5858d74-7vpwr -n itelastic-opns-58 -c weblogic-operator --request-timeout="20s" -- /bin/bash -c 'curl  --connect-timeout 20 --max-time 20 -X GET http://elasticsearch.default.svc.cluster.local:9200/logstash-2020.04.28/_search?q=log:itelastic-domain-59-admin-server'>
<04-28-2020 01:48:11> <INFO> <oracle.kubernetes.operator.utils.TestUtils exec> <
Command kubectl exec -it weblogic-operator-cf5858d74-7vpwr -n itelastic-opns-58 -c weblogic-operator --request-timeout="20s" -- /bin/bash -c 'curl  --connect-timeout 20 --max-time 20 -X GET http://elasticsearch.default.svc.cluster.local:9200/logstash-2020.04.28/_search?q=log:itelastic-domain-59-admin-server'
return value: 6
stderr = Unable to use a TTY - input is not a terminal or the right kind of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: elasticsearch.default.svc.cluster.local; Unknown error
command terminated with exit code 6
stdout = >
<04-28-2020 01:48:11> <INFO> <oracle.kubernetes.operator.BaseTest createResultAndPvDirs> <Adding file handler, logging to file at /var/lib/jenkins/workspace/weblogic-kubernetes-operator-quicktest/RESULT_ROOT/ItElasticLogging/acceptance_test_tmp/ItElasticLogging.out>
```

The latest commit fixes this by changing the call to `ExecCommand.exec()`

**Comment by markxnelson** [comment]
test run https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1388/ had another failure, missed a TestUtils.exec - have updated that, and queued up a new test run 1391

**Pull request merged**
