### PR TITLE
OWLS-76624 (Resolves #1228) - Introspector pod not picking up the container context from the domain resource

### LINKED ISSUE #1228: Introspector pod not picking up the container context from the domain resource
https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-resource/#pod-generation

"The job pod for the introspector is generated using the serverPod entries for the administration server", however, the `containerSecurityContext` from the `serverPod` is not being applied to the introspector pod where it is applied to the admin and managed servers.

### PR DESCRIPTION
**Pull request by alai8**
Introspector job now start with podSecurityContext and containerSecurityContext values from serverPod if configured.

In addition, introspector job now also apply the following serverPod configuration:
- resources
- affinity
- nodeSelector
- nodeName
- schedulerName
- priorityClassName
- runtimeClassName
- tolerations

Added unit tests.

passed jenkins http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2535/testReport/

### CODE REVIEW

**Comment by TheFrogPad** [comment]
FYI for @alai8 and @tbarnes-us I updated the description to include GitHub keyword so the corresponding issue is closed when PR is merged which is very convenient.  See https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by rjeberhard** [comment]
@alai8, I was going to help on the conflict resolve, but I don't know what happened with the patch matching code.

**Comment by alai8** [comment]
> @alai8, I was going to help on the conflict resolve, but I don't know what happened with the patch matching code.

looking into it

**Comment by russgold** [comment]
@alai @rjeberhard In my latest change, which I hope to push as a PR shortly, I have massively simplified the patch matching (and incorporated Ryan's client update), by switching to in-memory updates rather than expectation matching. If you have trouble resolving the conflict, it _might_ be simpler if my change goes in ahead of this one.

**Comment by rjeberhard** [comment]
@russgold, that's fine with me.  @alai8?

**Comment by alai8** [comment]
sure

**Comment by alai8** [comment]
@rjeberhard merged with Russ' changes.Passed quicktest http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2556/  Should be ready for merging.  Thanks

**Pull request merged**
