### PR TITLE
WIP: SSL enabling for a WLS domain

### PR DESCRIPTION
**Pull request by qvdang**
Test result @ http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3697/
using https://github.com/oracle/weblogic-kubernetes-operator/tree/12-12-2019_develop_OWLS-76552 and https://github.com/qvdang/docker-images

### CODE REVIEW

**Comment by rjeberhard** [comment]
I can't remember if there was some reason we were waiting to review this.  @mriccell, do you know?

**Comment by qvdang** [comment]
@rjeberhard There are some failures when running the full integration tests with this PR.  I'll get back to this task hopefully this week to make some further updates to resolve those. Thanks.

**Comment by bsmoyers** [comment]
Can one of the admins verify this patch?

**Comment by qvdang** [comment]
So I ran the tests in Jenkins(internal) several times with 12-12-2019_develop_OWLS-76552 & https://github.com/qvdang/docker-images:
1. #4028(PARALLEL_RUN) : 1 test failure (oracle.kubernetes.operator.ItOperator.testDomainOnPvUsingWlst)
2. #4030(PARALLEL_RUN unchecked): no test failure
3. #4037(ItOperator, the failed test in #4028, as IT_CLASS) : no failure

**Comment by qvdang** [comment]
A different test failed in another build:
ItJrfPvWlst.testJrfDomainOnPvUsingWlst in build #4042.

**Comment by qvdang** [comment]
8 failures(seemed random) with the External Jenkins: http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/923/testReport/oracle.kubernetes.operator

FAILURE: Timeout - pod monexp-domainns-5-admin-server output does not contain '1/1'

FAILURE: Timeout - pod d1onpv-admin-server output does not contain 'Running'

Error: UPGRADE FAILED: "operator-upgrade220" has no deployed releases

Error: could not find tiller

FAILURE: Timeout - pod domainpodsshutdown-admin-server output does not contain 'Running'

FAILURE: Kubectl command kubectl get domain domainpodsshutdown -n itpodsshutdown-domainns-39 -o jsonpath='{.spec.clusters[?(@.clusterName == "cluster-1")].replicas }' failed error: the server doesn't have a resource type "domain"

FAILURE: Kubectl command kubectl get domain domainpodsshutdown -n itpodsshutdown-domainns-39 -o jsonpath='{.spec.clusters[?(@.clusterName == "cluster-1")].replicas }' failed error: the server doesn't have a resource type "domain"

**Pull request closed without merging**
