### PR TITLE
Update WLS AKS Domain on PV guidance for memory considerations

### PR DESCRIPTION
**Pull request by galiacheng**
For #2415 

- Add note for memory customization.
- Increate default memory
  -  memory: 1.5Gi

### CODE REVIEW

**Comment by edburns** [comment]
Reviewing now.

**Comment by edburns** [comment]
Discussed in 2021-06-23 Weekly meeting
- Ed will do copyediting.
- Use WebLogic Server instead of WLS.
- @rjeberhard recommends including an inline example YAML of the **domain.yaml** showing the values literally in place.
   - Set the **request** and **limit** as the same.  This means that a pod, [once scheduled, won't get evicted](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed).  If the **request** and **limit** are different, then the **limit** should always be higher.

**Comment by edburns** [comment]
@galiacheng  please convert this to a draft PR for now.  Some more work is in progress.

**Comment by edburns** [comment]
Hello @galiacheng , can you please grant me push permission to your fork?  In the meantime, I'll attach a patch.
[0001-On-branch-galiacheng-main-Apply-lessons-from-2021-06.patch.gz](https://github.com/oracle/weblogic-kubernetes-operator/files/6705209/0001-On-branch-galiacheng-main-Apply-lessons-from-2021-06.patch.gz)

**Review by edburns — APPROVED** [review]

**Review by mriccell — APPROVED** [review]

**Review by rjeberhard — APPROVED** [review]

**Pull request merged**
