### PR TITLE
Added anti affinity to the wls pods

### PR DESCRIPTION
**Pull request by marinakog**
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2994

### CODE REVIEW

**Review by anpanigr — APPROVED** [review]
LGTM  based on kind nightly result.

**Comment by vanajamukkara** [comment]
have you verified that the pods are running on different nodes with these changes? Can you update with OKE jenkins results.

**Review by xiancao — APPROVED** [review]
LGTM

**Review by anpanigr — COMMENTED** [review]
@vanajamukkara  we can write an explicit test to verify the distribution of pod across nodes.  We need to skip test while running locally where the node count is one. I have a backlog JIRA to address it.  Marina can you verify the Pod Distribution manually on OKE cluster.

**Pull request merged**
