### PR TITLE
Publish operator helm chart on our GitHub page

### PR DESCRIPTION
**Pull request by jchermos**
https://jira.oraclecorp.com/jira/browse/OWLS-69849

Create helm repository to be accessed by github project pages. These changes need to be in gh-pages to be served by https://oracle.github.io/weblogic-kubernetes-operator. 

These changes contains:

- Create index.yaml file in operator charts folder.

- Add packaged helm chart weblogic-operator-2.tgz

### CODE REVIEW

**Comment by rjeberhard** [comment]
Hi Carlos,

We need to make some changes to this PR:
- We aren't using gh_pages, instead our project publishes content under `docs` from the master branch to https://oracle.github.io/weblogic-kubernetes-operator/.
- I'd like to generate the Helm chart package as part of the build and copy it to a directory under docs, such as docs/charts
- Finally, we need to document the steps to use the Helm chart without cloning the repository, e.g. 

helm repo add weblogic-operator https://oracle.github.io/weblogic-kubernetes-operator/charts
helm repo update
helm install weblogic-operator/weblogic-operator-2 ...

**Comment by jchermos** [comment]
> 
> 
> Hi Carlos,
> 
> We need to make some changes to this PR:
> 
>     * We aren't using gh_pages, instead our project publishes content under `docs` from the master branch to https://oracle.github.io/weblogic-kubernetes-operator/.
> 
>     * I'd like to generate the Helm chart package as part of the build and copy it to a directory under docs, such as docs/charts
> 
>     * Finally, we need to document the steps to use the Helm chart without cloning the repository, e.g.
> 
> 
> helm repo add weblogic-operator https://oracle.github.io/weblogic-kubernetes-operator/charts
> helm repo update
> helm install weblogic-operator/weblogic-operator-2 ...

I pushed the changes to generate the helm chart package during build. Where would you like me to put the usage steps?

**Comment by jchermos** [comment]
@rjeberhard  All requested changes done.

**Comment by rjeberhard** [comment]
@jchermos, did you see my message in slack this morning?  You have done everything I asked for.  So, first, thanks.  There is an issue that if you build repeatedly, then the helm package and repo index are different every time.  So, if we commit this PR, then other developers will constantly see these files change.  Sadly, I can't find a set of arguments to helm package that produce the same .tgz file every time and the index has both a created and generated time stamp.  Ideas?

**Comment by jchermos** [comment]
> 
> 
> @jchermos, did you see my message in slack this morning? You have done everything I asked for. So, first, thanks. There is an issue that if you build repeatedly, then the helm package and repo index are different every time. So, if we commit this PR, then other developers will constantly see these files change. Sadly, I can't find a set of arguments to helm package that produce the same .tgz file every time and the index has both a created and generated time stamp. Ideas?

Haha, sorry Ryan, didn't saw your message... I can move the create package process to a maven profile so it is created only with the profile.

**Comment by rjeberhard** [comment]
I have an idea...  I could get the latest modified time of any file under kubernetes/charts/weblogic-operator and compare that to the .tgz.  Then, only helm package and repo index if there is a later source file.

**Comment by rjeberhard** [comment]
Let me give that a try and then we'll fall back on the profile.

**Comment by rjeberhard** [comment]
@jchermos, what do you think of this:
`
#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" > /dev/null 2>&1 ; pwd -P )"
WOCHARTPATH="$SCRIPTPATH/charts/weblogic-operator"

if uname | grep -q "Darwin"; then
    mod_time_fmt="-f %m"
else
    mod_time_fmt="-c %Y"
fi

# Find latest file in source directory
unset -v latest
for file in "$WOCHARTPATH"/*; do
  [[ $file -nt $latest ]] && latest=$file
done

srctime="$(stat $mod_time_fmt $latest)"

out="$(helm package $WOCHARTPATH -d target)"
helm_package=$(echo $out | cut -d ':' -f 2)

dsttime="$(stat $mod_time_fmt $SCRIPTPATH/../docs/charts/$helm_package)"

if [ $srctime \> $dsttime ];
then
  helm repo index $WOCHARTPATH/ --url https://oracle.github.io/weblogic-kubernetes-operator/charts

  cp $WOCHARTPATH/index.yaml $SCRIPTPATH/../docs/charts
  mv $helm_package $SCRIPTPATH/../docs/charts/
fi;
`

**Comment by rjeberhard** [comment]
@jchermos, what do you think of this:

`#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" > /dev/null 2>&1 ; pwd -P )"
WOCHARTPATH="$SCRIPTPATH/charts/weblogic-operator"

if uname | grep -q "Darwin"; then
    mod_time_fmt="-f %m"
else
    mod_time_fmt="-c %Y"
fi

# Find latest file in source directory
unset -v latest
for file in "$WOCHARTPATH"/*; do
  [[ $file -nt $latest ]] && latest=$file
done

srctime="$(stat $mod_time_fmt $latest)"

out="$(helm package $WOCHARTPATH -d target)"
helm_package=$(echo $out | cut -d ':' -f 2)

dsttime="$(stat $mod_time_fmt $SCRIPTPATH/../docs/charts/$helm_package)"

if [ $srctime \> $dsttime ];
then
  helm repo index $WOCHARTPATH/ --url https://oracle.github.io/weblogic-kubernetes-operator/charts

  cp $WOCHARTPATH/index.yaml $SCRIPTPATH/../docs/charts
  mv $helm_package $SCRIPTPATH/../docs/charts/
fi;



`

**Comment by jchermos** [comment]
> 
> 
> I have an idea... I could get the latest modified time of any file under kubernetes/charts/weblogic-operator and compare that to the .tgz. Then, only helm package and repo index if there is a later source file.

Pushed the changes you suggested with some changes.

**Pull request merged**
