### PR TITLE
remove "if __name__ == 'main':" in the python scripts used in test 

### PR DESCRIPTION
**Pull request by xiancao**
With WLS 14.1.1.0 image, the test ItParameterizedDomain#testParamsScaleClustersWithRestApi failed in the domain type domain on pv. The root cause is that in WLS 1411 the usage of "main" of python script got changed. This change caused the application failed to deploy using  the file integration-tests/src/test/resources/python-scripts/application-deployment.py.

See the release note: https://docs.oracle.com/en/middleware/standalone/weblogic-server/14.1.1.0/wlsrn/issues.html#GUID-2F716208-D9A4-4586-91E8-A340DCD0CBF0

This PR removed "if __name__ == 'main':" clause in the python scripts used in test.

Jenkins run:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2571/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2574/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2648/

with 14.1.1.0-8 image:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2652/ (test failures are due to a known bug)
with 14.1.1.0-11 image:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2651/ (test failures are due to a known bug)

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Can u run the test against both 
   phx.ocir.io/weblogick8s/stage/weblogic:14.1.1.0-11
   phx.ocir.io/weblogick8s/stage/weblogic:14.1.1.0-8

**Comment by xiancao** [comment]
I submitted the job with WLS image 14.1.1.0-11 and 14.1.1.0-8. Found an introspect issue with 14.1.1.0. Sankar filed a bug for that: https://jira.oraclecorp.com/jira/browse/OWLS-85530

**Review by sankarpn — APPROVED** [review]
LGTM

**Review by anpanigr — APPROVED** [review]
LGTM

**Pull request merged**
