### PR TITLE
Port tests in main branch profile wko-okd-wls-mrg to release/3.4

### PR DESCRIPTION
**Pull request by sankarpn**
Port the following tests in main branch profile wko-okd-wls-mrg to release/3.4

                  **/ItCoherenceTests,
                  **/ItConfigDistributionStrategy,
                  **/ItDedicatedMode,
                  **/ItExternalLbTunneling,
                  **/ItExternalNodePortService,
                  **/ItInitContainers,
                  **/ItIntrospectVersion,
                  **/ItLiftAndShiftFromOnPremDomain,
                  **/ItLivenessProbeCustomization,
                  **/ItManagedCoherence,
                  **/ItManageNameSpace,
                  **/ItMiiDynamicUpdate*,
                  **/ItMiiCustomSslStore,
                  **/ItMiiSampleWlsAux,
                  **/ItMiiSampleWlsMain,
                  **/ItOperatorRestart,
                  **/ItPodsShutdownOption,
                  **/ItPodTemplates,
                  **/ItProductionSecureMode,
                  **/ItRemoteConsole,
                  **/ItServerStartPolicy,
                  **/ItServiceStartPolicyDynamicCluster,
                  **/ItServerStartPolicyConfigCluster,
                  **/ItSessionMigration,
                  **/ItStickySession,
                  **/ItSystemResOverrides,
                  **/ItMonitoringExporterWebApp,
                  **/ItMonitoringExporterSideCar,
                  **/ItMonitoringExporterSamples,
                  **/ItUsabilityOperatorHelmChart

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10186/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10187/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10188/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10189/

https://build.weblogick8s.org:8443/job/wko-okd-test/289/
https://build.weblogick8s.org:8443/job/wko-okd-test/290/

### CODE REVIEW

**Review by robertpatrick — CHANGES_REQUESTED** [review]
There is still one test failing in the PR gate:

[oracle.weblogic.kubernetes.ItManageNameSpace.testNameSpaceManageByRegularExpression](https://build.weblogick8s.org:8443/job/WebLogic%20Kubernetes%20Operator%20Kind/view/change-requests/job/PR-2989/5/testReport/oracle.weblogic.kubernetes/ItManageNameSpace/testNameSpaceManageByRegularExpression/)

**Review by rjeberhard — APPROVED** [review]
Assuming that the gating tests issue that Robert mentioned is resolved, I otherwise approve of the code changes.

**Comment by anpanigr** [comment]
Since the failure related to ItManageNameSpace class is not specific to OKD, We can temporarily comment the class from gating test and merge the PR to unblock the OpenShift Certification. We will create a separate JIRA to track the gating test failure.

**Comment by sankarpn** [comment]
> Since the failure related to ItManageNameSpace class is not specific to OKD, We can temporarily comment the class from gating test and merge the PR to unblock the OpenShift Certification. We will create a separate JIRA to track the gating test failure.

I have excluded the ItManageNamespace tests from running in OKD profiles. We can work fixing the failure after this PR is merged.

**Review by robertpatrick — APPROVED** [review]

**Pull request merged**
