### PR TITLE
Trust all certificates when connecting to the management REST interface from the operator

### PR DESCRIPTION
**Pull request by rjeberhard**
Creating as a draft for visibility to @russgold and @doxiao.

### CODE REVIEW

**Review by russgold — COMMENTED** [review]
It looks a bit more than is needed. This is what I have seen recommended (and use now in the exporter):

```
        private SSLContext createSSLContext() throws GeneralSecurityException {
            return SSLContexts.custom()
                .loadTrustMaterial(null, createAcceptingTrustStrategy())
                .build();
        }

        private TrustStrategy createAcceptingTrustStrategy() {
            return (cert, authType) -> true;
        }
```

**Comment by rjeberhard** [comment]
@russgold, I thought that the exporter was using Apache client. This is using the JDK's client. I've tried with less than what I have here and it didn't work.

**Comment by russgold** [comment]
Yes, the exporter uses the Apache client - which uses the JDK's security mechanisms. Did you try what I suggested, just setting up the SSLContext as described?

**Comment by rjeberhard** [comment]
The SSLContexts class is from the Apache library. I looked through the code behind that call and it's fairly similar to what I have.

**Review by russgold — APPROVED** [review]

**Pull request merged**
