### PR TITLE
Infra: Refactor TwoDomainLoadBalancer class

### PR DESCRIPTION
**Pull request by hzhao-github**
Currently TwoDomainLoadBalancer test class has method  testDeployAppAndInstallIngressControllers()  which install all three lb ingress  and  deploy the clusterView application.

When one of the loadbalancers fails to install, all the test fail, as each test uses the cluster view application to verify inter-server communication.  If ngnix installation fails, traefik and apache tests also fails. 

So we need to  de associate each test methods to be independent of all type of  lb igrress installation. 

Jenkin Run(s) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7137/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/71334

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Can we avoid the Ordering of the tests in the class.

**Comment by hzhao-github** [comment]
I'd not recommend removing the ordering because if we do so, we need to move installation of three LBers to BeforeAll. Then we go back to where we have this change -- when one installation of LBer failed, entire tests fail

**Review by anpanigr — COMMENTED** [review]
All the LoadBalancer tests ( 3 to 15)  depends on Test(2) i.e.  
testTwoDomainsManagedByOneOperatorSharingPV because Test(1) creates TwoDomains and shutdown both.  
How the NGINX tests depends on Traefik if you consider Ordering in needed.

**Comment by hzhao-github** [comment]
You are right that all LBers related tests have to be done after order(1) and order(2). However, in order to remove the ordering, we have to install all three LBers before all tests (except 1 & 2) start, that strategy bring back the issue of one LBer failed to install, no test will run. It doesn't matter whether 5 depends on 4, I just didn't touch the original ordering. If you don't like it, I can re-order to group same LBer test together.

**Review by anpanigr — COMMENTED** [review]
The other option is create separate class for each LB. Move the Test(1) and Test(2) to a separate class.  For each LoadBalancer class  beforeAll() create two domains and install the LoadBalancer, then all tests are independent.

We need a separate JIRA to accomplish this. Can you try to fails the Ngix LoadBalancer installation  and make sure that Traefik and Apache test works fine.

**Review by anpanigr — APPROVED** [review]
LGTM

**Comment by hzhao-github** [comment]
I changed NGINX namespace to force installing NGINX fail,

nginxHelmParams = installAndVerifyNginx(nginxNamespace + "123", 0, 0);
 
 The results are expected, only NIGNX related tests failed all other tests passed

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ItTwoDomainsLoadBalancers.testNginxTLSPathRoutingAdminServer:356->installIngressController:1928 [Test NGINX installation succeeds] NGINX installation is failed
[ERROR] Errors: 
[ERROR]   ItTwoDomainsLoadBalancers.testNginxHttpHostRoutingAcrossDomains:513->getNginxLbNodePort:1551 NullPointer
[ERROR]   ItTwoDomainsLoadBalancers.testNginxHttpsHostRoutingAcrossDomains:531->getNginxLbNodePort:1551 NullPointer
[ERROR]   ItTwoDomainsLoadBalancers.testNginxPathRoutingAcrossDomains:547->getNginxLbNodePort:1551 NullPointer
[ERROR]   ItTwoDomainsLoadBalancers.testNginxTLSPathRoutingAcrossDomains:382->getNginxLbNodePort:1551 NullPointer
[INFO] 
[ERROR] Tests run: 15, Failures: 1, Errors: 4, Skipped: 0
[INFO]

**Review by vanajamukkara — APPROVED** [review]
LG

**Pull request merged**
