### PR TITLE
Clean up logic to setup helm repo repository for prometheus and grafana

### PR DESCRIPTION
**Pull request by marinakog**
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3498/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3503/ - full run ( has same failures as develop)

### CODE REVIEW

**Review by anpanigr — APPROVED** [review]

**Comment by xiancao** [comment]
Looks good to me. Can you run the whole integration test suite in Jenkins and update the results here?

**Comment by vanajamukkara** [comment]
@marinakog you need to modify the copyright for all the files you modified to include year 2021

**Comment by rjeberhard** [comment]
I did a bulk update in the develop branch. If you merge latest changes then you will have updated copyright headers for all files.

**Comment by marinakog** [comment]
> Looks good to me. Can you run the whole integration test suite in Jenkins and update the results here?

I have updated with full suite run ( https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3503/) same failures as develop

**Review by xiancao — APPROVED** [review]

**Review by rjeberhard — APPROVED** [review]

**Pull request merged**
