### PR TITLE
Owls 75227 - simplify debugging the operator

### PR DESCRIPTION
**Pull request by russgold**
This change:
* simplifies putting the operator into debug by disabling the probes when debug is enabled, and
* allows the operator to be set not to suspend, meaning that a developer can attach after it is running. This is controlled by the `haltOnDebugStartup` setting.

Note that the default behavior is, as before, that the operator halts on startup when debug is enabled. I think that the default should be changed to _not_ halt, but did not make that change, here. @rjeberhard what do you think?

### CODE REVIEW

**Comment by pfmackin** [comment]
From a functional viewpoint it looks like there are 2 changes:

1) Automatically disable liveness / readiness probe if remote debugging enabled
2) Allow operator to run without halting in debug mode.

Is that correct?

**Comment by russgold** [comment]
Yes; that's correct.

**Comment by rjeberhard** [comment]
> I think that the default should be changed to not halt, but did not make that change, here. @rjeberhard what do you think?

I agree.  When we were first working with the operator, we had to frequently debug operator start-up.  Now, that is much less common and debugging use cases are almost always of the operator's response to some later change (namespace deleted, domain resource changed, etc.)  So, I'd be fine with the default being that the operator doesn't suspect.

I would prefer saying "suspend on startup" or not as "halt" sounds permanent.

**Comment by russgold** [comment]
Replaced with PR #1156

**Pull request closed without merging**
