### PR TITLE
Refactoring CommonTestUtils class Part1 : OperatorUtils, ImageUtils, LoadBalancerUtils, LogginExporterUtils, MonitoringUtils

### PR DESCRIPTION
**Pull request by marinakog**
Refactoring CommonTestUtils class Part1 : OperatorUtils, ImageUtils, LoadBalancerUtils, LogginExporterUtils, MonitoringUtils. Other utils objects will be refactored in part2
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5831/

OKE results:
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/372

### CODE REVIEW

**Review by maggiehe00 — APPROVED** [review]

**Comment by maggiehe00** [comment]
LGTM

**Review by sankarpn — COMMENTED** [review]
Hi @marinakog please run the tests against OKE cluster as well.

**Review by vanajamukkara — COMMENTED** [review]
LG, please update with OKE Jenkins results.

**Review by hzhao-github — APPROVED** [review]

**Comment by hzhao-github** [comment]
LGTM

**Comment by marinakog** [comment]
here are OKE results: https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/372

**Review by rjeberhard — APPROVED** [review]

**Pull request merged**
