### PR TITLE
 Moving SOA deployment samples to a different repo

### PR DESCRIPTION
**Pull request by sbattagi**
Hi,

This PR is to  delete SOA deployment samples from this repository and point the users to the actual SOA external repository (fmw-kubernetes). 

Please review and merge.

Thanks
Samba

### CODE REVIEW

**Review by mriccell — APPROVED** [review]

**Review by rjeberhard — APPROVED** [review]
Approving, but don't we want this to be committed to master?

**Comment by mriccell** [comment]
> Approving, but don't we want this to be committed to master?

Let's coordinate with @rdas0405

**Comment by rjeberhard** [comment]
What did we decide on develop vs. master? If you choose develop then this won't go into master until we release operator version 3.1. If you choose master, then it will become live immediately and I'll make sure that it gets merged to develop.

**Comment by sbattagi** [comment]
> 
> 
> What did we decide on develop vs. master? If you choose develop then this won't go into master until we release operator version 3.1. If you choose master, then it will become live immediately and I'll make sure that it gets merged to develop.

Yes, this should go to Master branch as well (Confirmed with @rdas0405 ).

**Pull request merged**
