### PR TITLE
Modify AKS mii sample to use auxiliary image.

### PR DESCRIPTION
**Pull request by galiacheng**
Modify AKS mii sample to use auxiliary image.

### Documentation Refactoring:

* **Sign-in Procedure**:
  - Replaced inline Azure CLI sign-in steps with a reference to `sign-in-azure.txt` to centralize the sign-in instructions. [[1]](diffhunk://#diff-4b631c4656f6227728e795700a13a14dae1f355119c470caf6c7e53a8e5a8006L60-R60) [[2]](diffhunk://#diff-ddb4d6dff6b2824f29e3f142f66a07a984d31647f17d205df4644b64fc7f8b75R1-R26)

* **Image Creation Instructions**:
  - Replaced detailed image creation steps with references to `auxiliary-image-directory.txt` and `run-mii-to-create-auxiliary-image.txt` to standardize the image creation process across different documentation sections. [[1]](diffhunk://#diff-4b631c4656f6227728e795700a13a14dae1f355119c470caf6c7e53a8e5a8006L141-R116) [[2]](diffhunk://#diff-4b631c4656f6227728e795700a13a14dae1f355119c470caf6c7e53a8e5a8006L173-R149) [[3]](diffhunk://#diff-57548ea462df20b6c5e277615cca89d608ffec776f3f92f9aaa8410ec5d03ba3R1-R4) [[4]](diffhunk://#diff-612aea9cfd1935025460c6da3572bf461769f806dc7abc5d0242aea6ee51898fR1-R40) [[5]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeL184-R193) [[6]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeL234-R226)

### Content Organization:

* **Parameter Preparation**:
  - Changed the heading from "Prepare parameters" to "##### Prepare parameters" for consistency in the documentation structure.

* **Namespace and Secrets**:
  - Added sections for creating Kubernetes secrets for WebLogic images and WebLogic itself, improving clarity on the required steps. [[1]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeR255-R259) [[2]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeR286-R302) [[3]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeR360-R397)

### Miscellaneous:

* **Minor Adjustments**:
  - Removed redundant instructions and added references to existing documentation for better clarity and reduced redundancy. [[1]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeR168) [[2]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeL295-R245)
  - Updated the sample directory setup instructions to ensure a clean environment. [[1]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeR34-R53) [[2]](diffhunk://#diff-515cf9bda070856983f243d1aae88e16304f00be841f37b1ad87e6263af0beaeL184-R193)

These changes enhance the documentation by making it more modular, reducing duplication, and ensuring that updates to common procedures are easier to manage.

### CODE REVIEW

**Comment by galiacheng** [comment]
Hello @rjeberhard this PR includes updates to the documentation and sample script. The documentation change is tied to the sample script. When merging, could you also update the sample-script.zip in release 4.2.5? Please let me know if you'd prefer me to create a separate PR for release 4.2. Thanks.

**Comment by edburns** [comment]
> Modify AKS mii sample to use auxiliary image.
> 
> ### Documentation Refactoring:
...
> These changes enhance the documentation by making it more modular, reducing duplication, and ensuring that updates to common procedures are easier to manage.

These annotated comments make reviewing very easy and more accurate. Was it a lot of work to create a commit log message that has the hyperlinks to the commits?

**Review by edburns — APPROVED** [review]

**Comment by galiacheng** [comment]
> Was it a lot of work to create a commit log message that has the hyperlinks to the commits?

Copilot generated the PR description @edburns

**Comment by edburns** [comment]
> > Was it a lot of work to create a commit log message that has the hyperlinks to the commits?
> 
> Copilot generated the PR description @edburns

I figured it was something like that. Did you have to ask for it? If so, how?

**Comment by galiacheng** [comment]
> I figured it was something like that. Did you have to ask for it? If so, how?

I selected **Copilot** and then **Summary**, and Copilot generated a highly detailed description. I removed the summary and retained the content for the changes, as you saw :).

image

**Pull request merged**
