### PR TITLE
Modified  DomainInImage Upgrade usecase  

### PR DESCRIPTION
**Pull request by anpanigr**
Modified the DomainInImage usecases to 
   a) use k8s API to create domain resource, instead of hard-coded domain.yaml file
   b) removed the commented Operator Release upgrade such as 2.5.0/2.6.0 

Jenkin Upgrade Test 

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6423/   ( Operator WLS upgrade) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6424    ( All upgrade )

### CODE REVIEW

**Review by vanajamukkara — APPROVED** [review]
LG

**Review by sankarpn — APPROVED** [review]
LGTM

**Review by maggiehe00 — APPROVED** [review]
LGTM

**Comment by tbarnes-us** [comment]
Just verifying: Note that this change did not remove the domain.yaml file.

**Comment by anpanigr** [comment]
> Just verifying: Note that this change did not remove the domain.yaml file.

The file has been removed an earlier https://github.com/oracle/weblogic-kubernetes-operator/pull/2526
Due to this reason the DomainInImage upgrade tests are failing, since it was using the hard-coded domain.yaml file

**Pull request merged**
