### PR TITLE
minor oper unit test fix: cleanup tmp files once done with them

### PR DESCRIPTION
**Pull request by tbarnes-us**
Fix two operator unit tests that were leaving temp directories behind in /tmp...

### CODE REVIEW

**Review by alai8 — APPROVED** [review]
Looks good. Wondering if it is possible to delete the temp files during Memento.revert()?

**Comment by russgold** [comment]
I was not aware that we had any unit tests creating actual files. Is there a reason that we cannot use InMemoryFileSystem to avoid this? It is used in a fair number of tests and is faster than creating real files.

**Review by russgold — CHANGES_REQUESTED** [review]
> Please look at InMemoryFileSystem as an alternative.

Tom: Will do.

**Review by russgold — APPROVED** [review]
I'm not going to insist on that change before the 4.0 release

**Pull request merged**
