### PR TITLE
[wko-nightly](main): ItElasticLoggingFluentd tests fails due failure to create Elasticsearch deployment

### PR DESCRIPTION
**Pull request by hzhao-github**
No related failures seen 
from https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10317 
to https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10325
and https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10329

### CODE REVIEW

**Review by anpanigr — COMMENTED** [review]
Did u sync to the latest main ?
The issue related to ItServerStartPolicyDynamicCluster.testDynamicClusterScale  has been resolved.

**Comment by hzhao-github** [comment]
yes,

bash-4.2$ git merge origin/main
Already up-to-date.

**Review by rjeberhard — APPROVED** [review]

**Review by sankarpn — APPROVED** [review]
lgtm

**Review by anpanigr — COMMENTED** [review]
lgtm

**Review by anpanigr — APPROVED** [review]

**Pull request merged**
