### PR TITLE
OWLS-77556: replace complete env dump in pods/job with curated listin…

### PR DESCRIPTION
**Pull request by tbarnes-us**
…g of env var values

### CODE REVIEW

**Comment by alai8** [comment]
LGTM. A minor comment: does checkEnv currently print the env var? Should we modify checkEnv to not print the env var value if the env var is set, so we don't print the values an extra time?

**Comment by tbarnes-us** [comment]
> @alai8 wrote: A minor comment: does checkEnv currently print the env var? Should we modify checkEnv to not print the env var value if the env var is set, so we don't print the values an extra time?

There is some redundancy, but checkEnv has varied uses

**Comment by tbarnes-us** [comment]
> @alai8 wrote: A minor comment: does checkEnv currently print the env var? Should we modify checkEnv to not print the env var value if the env var is set, so we don't print the values an extra time?

Looking into it.

**Comment by tbarnes-us** [comment]
> > @alai8 wrote: A minor comment: does checkEnv currently print the env var? Should we modify checkEnv to not print the env var value if the env var is set, so we don't print the values an extra time?
> 
> Looking into it.

Done.

**Pull request merged**
