### PR TITLE
Owls83813 fix a scaling issue when upgrade from 2.5.0

### PR DESCRIPTION
**Pull request by doxiao**
Add a check to void NullPointerException; minDynamicClusterSize does not exist in 2.5.0 release. 
Remove the workaround in integration test case because the test passes now without the workaround.

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2010/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2028/

### CODE REVIEW

**Comment by vanajamukkara** [comment]
@doxiao please update the PR with jenkins results

**Review by lennyphan — APPROVED** [review]
LGTM

**Comment by alai8** [comment]
should we add a unit test even though the change is trivial? Thanks

**Comment by doxiao** [comment]
> should we add a unit test even though the change is trivial? Thanks
This is an upgrade use case, and we have an integration test case that covers this already. I think we are fine.

**Review by alai8 — APPROVED** [review]

**Review by vanajamukkara — APPROVED** [review]
LGTM

**Pull request merged**
